<?php

namespace App\Models;

use Exception;
use Closure;
use DateTimeInterface;
use Throwable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

/**
 * App\Models\BaseModel
 *
 * @method static \Illuminate\Database\Eloquent\Builder|BaseModel newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|BaseModel newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|BaseModel query()
 * @mixin \Eloquent
 */
class BaseModel extends Model
{
    use BooleanSoftDeletes;
    use HasFactory;

    public const CREATED_AT = 'add_time';
    public const UPDATED_AT = 'update_time';

    public $defaultCasts = [
        'deleted' => 'boolean'
    ];

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        parent::mergeCasts($this->defaultCasts);
    }

    public static function new()
    {
        return new static();
    }

    public function getTable()
    {
        return $this->table ?? Str::snake(class_basename($this)); // TODO: Change the autogenerated stub
    }

    public function toArray()
    {
        $items = parent::toArray();
        // 字段值为null 时过滤掉(日常开发不建议用)
        $items = array_filter($items, function ($item) {
            return !is_null($item);
        });
        $keys = array_keys($items);
        $keys = array_map(function ($key) {
            return lcfirst(Str::studly($key));
        }, $keys);
        $values = array_values($items);

        return array_combine($keys, $values);
    }

    // 把时间格式转换为我们的
    public function serializeDate(DateTimeInterface $date)
    {
        return Carbon::instance($date)->toDateTimeString();
    }

    /**
     * 封装乐观锁更新 compare and save
     * @return int
     * @throws Throwable
     */
    public function cas()
    {
        // 数据不存在
        throw_if(!$this->exists, Exception::class, 'data not exists when cas!');

        // 未被更新
        $dirty = $this->getDirty();
        if (empty($dirty)) {
            return 0;
        }

        // 添加update_time
        if ($this->usesTimestamps()) {
            $this->updateTimestamps();
            $dirty = $this->getDirty();
        }

        $diff = array_diff(array_keys($dirty), array_keys($this->original));
        throw_if(!empty($diff), Exception::class, 'key [' . implode(',', $diff) . '] not exists when cas!');

        if ($this->fireModelEvent('casing') === false) {
            return 0;
        }

        // newModelQuery 去掉where deleted = 0
        $query = $this->newModelQuery()->where($this->getKeyName(), $this->getKey());
        foreach ($dirty as $key => $value) {
            $query = $query->where($key, $this->getOriginal($key));
        }

        $row = $query->update($dirty);
        if ($row > 0) {
            $this->syncChanges();
            $this->fireModelEvent('cased', false);
            $this->syncOriginal();
        }

        return $row;
    }

    /**
     * Register a casing model event with the dispatcher.
     *
     * @param Closure|string $callback
     * @return void
     */
    public static function casing($callback)
    {
        static::registerModelEvent('casing', $callback);
    }

    /**
     * Register a cased model event with the dispatcher.
     *
     * @param Closure|string $callback
     * @return void
     */
    public static function cased($callback)
    {
        static::registerModelEvent('cased', $callback);
    }
}
